services:
 nginx:
  image: nginx
  restart: unless-stopped
  container_name: nginx
  volumes:
   - ./conf:/etc/nginx
  ports:
   - 80:80
  environment:
   - NGINX_HOST=http://127.0.0.1
   - NGINX_PORT=80
  depends_on:
   - backend
   - frontend
 frontend:
  build: ./frontend
  container_name: frontend
  ports:
   - target: 5000
     published: 5000
     protocol: tcp
     mode: host  
 backend:
  build: ./backend
  container_name: backend
  ports:
   - target: 8080
     published: 8080
     protocol: tcp
     mode: host
  environment:
   POSTGRES_HOST: postgresdb
   POSTGRES_PASSWORD: postgres
   POSTGRES_USER: postgres
   POSTGRES_DATABASE: postgres
   REDIS_HOST: redis
   REQUEST_ORIGIN: http://localhost
  depends_on:
   - postgresdb
   - redis
 postgresdb:
  image: postgres:13.2-alpine
  restart: unless-stopped
  environment:
   POSTGRES_PASSWORD: postgres
   POSTGRES_USER: postgres
   POSTGRES_DB: postgres
  container_name: postgresdb
 redis:
  image: redis
  container_name: redis
  command: ["redis-server"]
 
 
